import type { Product, Promotion, ProductPromotion } from "./types"

// Logo da loja (altere o caminho ou link para a logo desejada)
export const LOGO_URL = "https://i.ibb.co/fGSnH3hd/logoatacad-o.jpg" // Logo principal da loja

// Foto da entrada da loja (altere o caminho ou link para a foto desejada)
export const ENTRADA_URL = "/imagens/entrada-loja.jpg" // Foto da entrada da loja

export const products = [
  {
    id: "1",
    name: "ÁGUA MINERAL NATURAGUA 1,5L",
    price: 2.99,
    originalPrice: 2.30,
    image: "https://i.ibb.co/N65dsgfh/aguanaturagua1-5l.jpg ", // Água mineral
    category: "Bebidas",
    description: "Água mineral natural 1,5 litros",
    stock: 6,
    rating: 4.5,
    reviews: 12,
    brand: "Naturagua",
    unit: "1,5L",
    tags: ["bebida", "água", "mineral"],
  },
  {
    id: "2",
    name: "ÁGUA MINERAL NATURAGUA 500ML C/ GÁS",
    price: 1.99,
    originalPrice: 1.44,
    image: "https://i.ibb.co/p6WM3mnK/aguacomg-s.jpg", // Água com gás
    category: "Bebidas",
    description: "Água mineral com C/GÁS 500ml",
    stock: 12,
    rating: 4.3,
    reviews: 8,
    brand: "Naturagua",
    unit: "500ml",
    tags: ["bebida", "água", "gás"],
  },
  {
    id: "3",
    name: "ÁGUA MINERAL NATURAGUA 500ML S/ GÁS",
    price: 1.49,
    originalPrice: 1.08,
    image: "https://i.ibb.co/4gVp5kbz/aguasemg-s.jpg", // Água sem gás
    category: "Bebidas",
    description: "Água mineral sem gás 500ml",
    stock: 12,
    rating: 4.4,
    reviews: 15,
    brand: "Naturagua",
    unit: "500ml",
    tags: ["bebida", "água"],
  },
  {
    id: "4",
    name: "AMENDOIM EM BANDA CASTRO 1KG",
    price: 13.99,
    originalPrice: 13.49,
    image: "https://i.ibb.co/PZ9HLZrg/amendoimembanda.jpg", // Amendoim
    category: "Snacks",
    description: "Amendoim em banda tradicional 1kg",
    stock: 4,
    rating: 4.7,
    reviews: 25,
    brand: "Castro",
    unit: "1kg",
    tags: ["snack", "amendoim", "natural"],
  },
  {
    id: "5",
    name: "ARROZ BRANCO NAMORADO 1KG",
    price: 5.69,
    originalPrice: 5.29,
    image: "https://i.ibb.co/V0rGtJcP/arroznamorado.jpg", // Arroz branco
    category: "Grãos",
    description: "Arroz branco tipo 1 1kg",
    stock: 10,
    rating: 4.6,
    reviews: 45,
    brand: "Namorado",
    unit: "1kg",
    tags: ["arroz", "básico", "alimento"],
  },
  {
    id: "6",
    name: "ARROZ BRANCO PAI JOÃO 1KG",
    price: 5.49,
    originalPrice: 5.39,
    // Foto do produto: Arroz branco Pai João 1kg
    image: "https://i.ibb.co/gbzsG1wc/arrozbrancopaijo-o.jpg", // Arroz branco
    category: "Grãos",
    description: "Arroz branco tipo 1 1kg",
    stock: 10,
    rating: 4.5,
    reviews: 38,
    brand: "Pai João",
    unit: "1kg",
    tags: ["arroz", "básico", "alimento"],
  },
  {
    id: "7",
    name: "ARROZ BRANCO POP 1KG",
    price: 4.99,
    originalPrice: 4.99,
    // Foto do produto: Arroz branco Pop 1kg
    image: "https://i.ibb.co/8gc360YT/arrozbrancopop.jpg", // Arroz branco
    category: "Grãos",
    description: "Arroz branco tipo 1 1kg",
    stock: 10,
    rating: 4.4,
    reviews: 52,
    brand: "Pop",
    unit: "1kg",
    tags: ["arroz", "básico", "alimento"],
  },
  {
    id: "8",
    name: "ARROZ PARBOILIZADO CAMIL 1KG",
    price: 6.29,
    originalPrice: 5.99,
    // Foto do produto: Arroz parboilizado Camil 1kg
    image: "https://i.ibb.co/V8hkx53/arrozparboilizadocamil.jpg", // Arroz parboilizado
    category: "Grãos",
    description: "Arroz parboilizado 1kg",
    stock: 10,
    rating: 4.8,
    reviews: 67,
    brand: "Camil",
    unit: "1kg",
    tags: ["arroz", "parboilizado", "nutritivo"],
  },
  {
    id: "9",
    name: "ARROZ PARBOILIZADO EMOÇÕES 1KG",
    price: 5.99,
    originalPrice: 5.99,
    // Foto do produto: Arroz parboilizado Emoções 1kg
    image: "https://i.ibb.co/VpqNb9t9/arrozparboilizadoemo-es.jpg", // Troque para o link da foto real do produto
    category: "Grãos",
    description: "Arroz parboilizado 1kg",
    stock: 10,
    rating: 4.6,
    reviews: 29,
    brand: "Emoções",
    unit: "1kg",
    tags: ["arroz", "parboilizado", "nutritivo"],
  },
  {
    id: "10",
    name: "ARROZ PARBOILIZADO POP 1KG",
    price: 4.50,
    originalPrice: 4.30,
    // Foto do produto: Arroz parboilizado Pop 1kg
    image: "https://i.ibb.co/vCq3CkSx/arrozparboilizadopop.jpg", // Troque para o link da foto real do produto
    category: "Grãos",
    description: "Arroz parboilizado 1kg",
    stock: 30,
    rating: 4.5,
    reviews: 41,
    brand: "Pop",
    unit: "1kg",
    tags: ["arroz", "parboilizado", "nutritivo"],
  },
  {
    id: "11",
    name: "AZEITE DE OLIVA EXTRA VIRGEM COCINERO 250ML",
    price: 21.49,
    originalPrice: 21.49,
    // Foto do produto: Azeite de oliva extra virgem Cocinero 250ml
    image: "https://i.ibb.co/KxFd3J1C/azeitedeolivacocinero.jpg", // Azeite de oliva
    category: "Óleos",
    description: "Azeite de oliva extra virgem 250ml",
    stock: 5,
    rating: 4.9,
    reviews: 18,
    brand: "Cocinero",
    unit: "250ml",
    tags: ["azeite", "oliva", "extra virgem"],
  },
  {
    id: "12",
    name: "AZEITE DE OLIVA EXTRA VIRGEM COCINERO 500ML",
    price: 37.90,
    originalPrice: 36.90,
    // Foto do produto: Azeite de oliva extra virgem Cocinero 500ml
    image: "https://i.ibb.co/k2hKnsnX/azeitedeolivacocinero500ml.jpg", // Troque para o link da foto real do produto
    category: "Óleos",
    description: "Azeite de oliva extra virgem 500ml",
    stock: 10,
    rating: 4.9,
    reviews: 22,
    brand: "Cocinero",
    unit: "500ml",
    tags: ["azeite", "oliva", "extra virgem"],
  },
  {
    id: "13",
    name: "AZEITE DENDÊ MARIZA 200ML",
    price: 7.49,
    originalPrice: 6.49,
    // Foto do produto: Azeite de dendê Mariza 200ml
    image: "https://i.ibb.co/wZf7nKSB/azeitedendemariza200ml.jpg", // Troque para o link da foto real do produto
    category: "Óleos",
    description: "Azeite de dendê 200ml",
    stock: 12,
    rating: 4.3,
    reviews: 15,
    brand: "Mariza",
    unit: "200ml",
    tags: ["azeite", "dendê", "tradicional"],
  },
  {
    id: "14",
    name: "BACON EM CUBO KG",
    price: 29.90,
    originalPrice: 29.90,
    // Foto do produto: Bacon em cubo por kg
    image: "https://i.ibb.co/pvdqLP9d/baconemcubo.jpg", // Troque para o link da foto real do produto
    category: "Carnes",
    description: "Bacon em cubo por kg",
    stock: 8,
    rating: 4.7,
    reviews: 33,
    brand: "Frigorífico",
    unit: "kg",
    tags: ["bacon", "carne", "cubo"],
  },
  {
    id: "15",
    name: "BACON MANTA KG",
    price: 28.90,
    originalPrice: 28.90,
    // Foto do produto: Bacon em manta por kg
    image: "https://i.ibb.co/vvcYLN4g/baconmantakgjpeg.jpg", // Troque para o link da foto real do produto
    category: "Carnes",
    description: "Bacon em manta por kg",
    stock: 6,
    rating: 4.6,
    reviews: 28,
    brand: "Frigorífico",
    unit: "kg",
    tags: ["bacon", "carne", "manta"],
  },
  {
    id: "16",
    name: "BANDEJA DE MORANGO",
    price: 9.99,
    originalPrice: 9.49,
    // Foto do produto: Bandeja de morango fresco
    image: "https://exemplo.com/imagens/bandeja-de-morango.jpg", // Troque para o link da foto real do produto
    category: "Frutas",
    description: "Bandeja de morango fresco",
    stock: 4,
    rating: 4.8,
    reviews: 19,
    brand: "Frutas Frescas",
    unit: "bandeja",
    tags: ["fruta", "morango", "fresco"],
  },
  {
    id: "17",
    name: "BANDEJA DE OVOS BRANCOS COM 30 UNIDADES",
    price: 15.99,
    originalPrice: 15.49,
    // Foto do produto: Bandeja com 30 ovos brancos
    image: "https://exemplo.com/imagens/bandeja-de-ovos-brancos-30-unidades.jpg", // Troque para o link da foto real do produto
    category: "Laticínios",
    description: "Bandeja com 30 ovos brancos",
    stock: 10,
    rating: 4.5,
    reviews: 42,
    brand: "Granja",
    unit: "30 un",
    tags: ["ovos", "brancos", "frescos"],
  },
  {
    id: "18",
    name: "BARRA DE CHOCOLATE COBERTURA CONFEITEIRO BLEND MAVALERIO 1,01KG",
    price: 22.90,
    originalPrice: 22.90,
    // Foto do produto: Barra de chocolate para confeitaria Mavalério 1,01kg
    image: "https://exemplo.com/imagens/barra-de-chocolate-confeiteiro-blend-mavalerio-1-01kg.jpg", // Troque para o link da foto real do produto
    category: "Chocolates",
    description: "Barra de chocolate para confeitaria 1,01kg",
    stock: 6,
    rating: 4.9,
    reviews: 31,
    brand: "Mavalério",
    unit: "1,01kg",
    tags: ["chocolate", "confeitaria", "cobertura"],
  },
  {
    id: "19",
    name: "BARRA DE CHOCOLATE CONFEITEIRO AO LEITE HARALD 1,01KG",
    price: 23.90,
    originalPrice: 22.99,
    // Foto do produto: Barra de chocolate ao leite para confeitaria Harald 1,01kg
    image: "https://exemplo.com/imagens/barra-de-chocolate-confeiteiro-ao-leite-harald-1-01kg.jpg", // Troque para o link da foto real do produto
    category: "Chocolates",
    description: "Barra de chocolate ao leite para confeitaria 1,01kg",
    stock: 5,
    rating: 4.8,
    reviews: 27,
    brand: "Harald",
    unit: "1,01kg",
    tags: ["chocolate", "confeitaria", "leite"],
  },
  {
    id: "20",
    name: "BARRA DE CHOCOLATE CONFEITEIRO BLEND HARALD 1,01KG",
    price: 20.99,
    originalPrice: 19.99,
    // Foto do produto: Barra de chocolate blend para confeitaria Harald 1,01kg
    image: "https://exemplo.com/imagens/barra-de-chocolate-confeiteiro-blend-harald-1-01kg.jpg", // Troque para o link da foto real do produto
    category: "Chocolates",
    description: "Barra de chocolate blend para confeitaria 1,01kg",
    stock: 5,
    rating: 4.7,
    reviews: 24,
    brand: "Harald",
    unit: "1,01kg",
    tags: ["chocolate", "confeitaria", "blend"],
  },
  {
    id: "21",
    name: "BARRA DE CHOCOLATE CONFEITEIRO CHOCOLATE BRANCO HARALD 1,010KG",
    price: 24.99,
    originalPrice: 23.90,
    // Foto do produto: Barra de chocolate branco para confeitaria Harald 1,01kg
    image: "https://exemplo.com/imagens/barra-de-chocolate-confeiteiro-chocolate-branco-harald-1-010kg.jpg", // Troque para o link da foto real do produto
    category: "Chocolates",
    description: "Barra de chocolate branco para confeitaria 1,01kg",
    stock: 5,
    rating: 4.6,
    reviews: 21,
    brand: "Harald",
    unit: "1,01kg",
    tags: ["chocolate", "confeitaria", "branco"],
  },
  {
    id: "22",
    name: "BARRA DE CHOCOLATE CONFEITEIRO MEIO AMARGO HARALD 1,01KG",
    price: 23.90,
    originalPrice: 22.99,
    // Foto do produto: Barra de chocolate meio amargo para confeitaria Harald 1,01kg
    image: "https://exemplo.com/imagens/barra-de-chocolate-confeiteiro-meio-amargo-harald-1-01kg.jpg", // Troque para o link da foto real do produto
    category: "Chocolates",
    description: "Barra de chocolate meio amargo para confeitaria 1,01kg",
    stock: 5,
    rating: 4.8,
    reviews: 29,
    brand: "Harald",
    unit: "1,01kg",
    tags: ["chocolate", "confeitaria", "meio amargo"],
  },
  {
    id: "23",
    name: "BATATA BEM BRASIL MAIS BATATA 2KG",
    price: 29.90,
    originalPrice: 28.90,
    // Foto do produto: Batata especial Bem Brasil 2kg
    image: "https://exemplo.com/imagens/batata-bem-brasil-mais-batata-2kg.jpg", // Troque para o link da foto real do produto
    category: "Hortifruti",
    description: "Batata especial 2kg",
    stock: 7,
    rating: 4.6,
    reviews: 35,
    brand: "Bem Brasil",
    unit: "2kg",
    tags: ["batata", "hortifruti", "especial"],
  },
  {
    id: "24",
    name: "BATATA PALHA AGUA NA BOCA 140G",
    price: 4.49,
    originalPrice: 3.99,
    // Foto do produto: Batata palha Água na Boca 140g
    image: "https://exemplo.com/imagens/batata-palha-agua-na-boca-140g.jpg", // Troque para o link da foto real do produto
    category: "Snacks",
    description: "Batata palha 140g",
    stock: 10,
    rating: 4.4,
    reviews: 18,
    brand: "Água na Boca",
    unit: "140g",
    tags: ["batata", "palha", "snack"],
  },
  {
    id: "25",
    name: "BATATA PALHA AGUA NA BOCA 1KG",
    price: 23.90,
    originalPrice: 23.90,
    // Foto do produto: Batata palha Água na Boca 1kg
    image: "https://exemplo.com/imagens/batata-palha-agua-na-boca-1kg.jpg", // Troque para o link da foto real do produto
    category: "Snacks",
    description: "Batata palha 1kg",
    stock: 5,
    rating: 4.5,
    reviews: 12,
    brand: "Água na Boca",
    unit: "1kg",
    tags: ["batata", "palha", "snack"],
  },
  {
    id: "26",
    name: "BATATA PALHA AGUA NA BOCA 400G",
    price: 9.75,
    originalPrice: 8.99,
    // Foto do produto: Batata palha Água na Boca 400g
    image: "https://exemplo.com/imagens/batata-palha-agua-na-boca-400g.jpg", // Troque para o link da foto real do produto
    category: "Snacks",
    description: "Batata palha 400g",
    stock: 10,
    rating: 4.3,
    reviews: 16,
    brand: "Água na Boca",
    unit: "400g",
    tags: ["batata", "palha", "snack"],
  },
  {
    id: "27",
    name: "BATATA PALHA FEULEN 400G TRAD",
    price: 15.99,
    originalPrice: 14.99,
    // Foto do produto: Batata palha tradicional Feulen 400g
    image: "https://exemplo.com/imagens/batata-palha-feulen-400g-trad.jpg", // Troque para o link da foto real do produto
    category: "Snacks",
    description: "Batata palha tradicional 400g",
    stock: 6,
    rating: 4.7,
    reviews: 23,
    brand: "Feulen",
    unit: "400g",
    tags: ["batata", "palha", "tradicional"],
  },
  {
    id: "28",
    name: "BISNAGA CREAM CHEESE TRADICIONAL SABOR E VIDA 1.5KG",
    price: 59.90,
    originalPrice: 57.90,
    // Foto do produto: Cream cheese tradicional em bisnaga Sabor e Vida 1,5kg
    image: "https://exemplo.com/imagens/bisnaga-cream-cheese-tradicional-sabor-e-vida-1-5kg.jpg", // Troque para o link da foto real do produto
    category: "Laticínios",
    description: "Cream cheese tradicional em bisnaga 1,5kg",
    stock: 4,
    rating: 4.8,
    reviews: 19,
    brand: "Sabor e Vida",
    unit: "1,5kg",
    tags: ["cream cheese", "laticínio", "bisnaga"],
  },
  {
    id: "29",
    name: "BISNAGA CREME DE AVELLA COM CACAU 1,01 KG BOM PRINCIPIO",
    price: 39.90,
    originalPrice: 39.90,
    // Foto do produto: Creme de avelã com cacau em bisnaga Bom Princípio 1,01kg
    image: "https://exemplo.com/imagens/bisnaga-creme-de-avella-com-cacau-1-01-kg-bom-princípio.jpg", // Troque para o link da foto real do produto
    category: "Chocolates",
    description: "Creme de avelã com cacau em bisnaga 1,01kg",
    stock: 6,
    rating: 4.9,
    reviews: 31,
    brand: "Bom Princípio",
    unit: "1,01kg",
    tags: ["creme", "avelã", "cacau", "chocolate"],
  },
  {
    id: "30",
    name: "BISNAGA DE REQUEIJÃO JANGADA 1,5KG",
    price: 11.99,
    originalPrice: 10.99,
    // Foto do produto: Requeijão em bisnaga Jangada 1,5kg
    image: "https://exemplo.com/imagens/bisnaga-de-requeijão-jangada-1-5kg.jpg", // Troque para o link da foto real do produto
    category: "Laticínios",
    description: "Requeijão em bisnaga 1,5kg",
    stock: 6,
    rating: 4.5,
    reviews: 42,
    brand: "Jangada",
    unit: "1,5kg",
    tags: ["requeijão", "laticínio", "bisnaga"],
  },
  // Adicionando mais produtos
  {
    id: "31",
    name: "FEIJÃO PRETO CAMIL 1KG",
    price: 8.99,
    originalPrice: 8.49,
    // Foto do produto: Feijão preto Camil 1kg
    image: "https://exemplo.com/imagens/feijão-preto-camil-1kg.jpg", // Troque para o link da foto real do produto
    category: "Grãos",
    description: "Feijão preto tipo 1 1kg",
    stock: 15,
    rating: 4.7,
    reviews: 89,
    brand: "Camil",
    unit: "1kg",
    tags: ["feijão", "preto", "básico"],
  },
  {
    id: "32",
    name: "FEIJÃO CARIOCA CAMIL 1KG",
    price: 7.99,
    originalPrice: 7.49,
    // Foto do produto: Feijão carioca Camil 1kg
    image: "https://exemplo.com/imagens/feijão-carioca-camil-1kg.jpg", // Troque para o link da foto real do produto
    category: "Grãos",
    description: "Feijão carioca tipo 1 1kg",
    stock: 20,
    rating: 4.6,
    reviews: 156,
    brand: "Camil",
    unit: "1kg",
    tags: ["feijão", "carioca", "básico"],
  },
  {
    id: "33",
    name: "AÇÚCAR REFINADO UNIÃO 1KG",
    price: 4.99,
    originalPrice: 4.79,
    // Foto do produto: Açúcar refinado União 1kg
    image: "https://exemplo.com/imagens/açúcar-refinado-união-1kg.jpg", // Troque para o link da foto real do produto
    category: "Açúcar e Adoçantes",
    description: "Açúcar refinado 1kg",
    stock: 25,
    rating: 4.5,
    reviews: 203,
    brand: "União",
    unit: "1kg",
    tags: ["açúcar", "refinado", "básico"],
  },
  {
    id: "34",
    name: "AÇÚCAR CRISTAL UNIÃO 1KG",
    price: 4.49,
    originalPrice: 4.29,
    // Foto do produto: Açúcar cristal União 1kg
    image: "https://exemplo.com/imagens/açúcar-cristal-união-1kg.jpg", // Troque para o link da foto real do produto
    category: "Açúcar e Adoçantes",
    description: "Açúcar cristal 1kg",
    stock: 18,
    rating: 4.4,
    reviews: 67,
    brand: "União",
    unit: "1kg",
    tags: ["açúcar", "cristal", "básico"],
  },
  {
    id: "35",
    name: "LEITE INTEGRAL ITAMBÉ 1L",
    price: 5.99,
    originalPrice: 5.79,
    // Foto do produto: Leite integral Itambé 1L
    image: "https://exemplo.com/imagens/leite-integral-itambé-1l.jpg", // Troque para o link da foto real do produto
    category: "Laticínios",
    description: "Leite integral 1 litro",
    stock: 30,
    rating: 4.6,
    reviews: 234,
    brand: "Itambé",
    unit: "1L",
    tags: ["leite", "integral", "fresco"],
  },
  {
    id: "36",
    name: "PÃO DE FORMA WICKBOLD 500G",
    price: 8.99,
    originalPrice: 8.49,
    // Foto do produto: Pão de forma Wickbold 500g
    image: "https://exemplo.com/imagens/pão-de-forma-wickbold-500g.jpg", // Troque para o link da foto real do produto
    category: "Padaria",
    description: "Pão de forma tradicional 500g",
    stock: 12,
    rating: 4.5,
    reviews: 89,
    brand: "Wickbold",
    unit: "500g",
    tags: ["pão", "forma", "tradicional"],
  },
  {
    id: "37",
    name: "MACARRÃO ESPAGUETE CAMIL 500G",
    price: 3.99,
    originalPrice: 3.79,
    // Foto do produto: Macarrão espaguete Camil 500g
    image: "https://exemplo.com/imagens/macarrão-espaguete-camil-500g.jpg", // Troque para o link da foto real do produto
    category: "Massas",
    description: "Macarrão espaguete 500g",
    stock: 40,
    rating: 4.4,
    reviews: 156,
    brand: "Camil",
    unit: "500g",
    tags: ["macarrão", "espaguete", "massa"],
  },
  {
    id: "38",
    name: "MACARRÃO PENNE CAMIL 500G",
    price: 4.29,
    originalPrice: 4.09,
    // Foto do produto: Macarrão penne Camil 500g
    image: "https://exemplo.com/imagens/macarrão-penne-camil-500g.jpg", // Troque para o link da foto real do produto
    category: "Massas",
    description: "Macarrão penne 500g",
    stock: 35,
    rating: 4.5,
    reviews: 98,
    brand: "Camil",
    unit: "500g",
    tags: ["macarrão", "penne", "massa"],
  },
  {
    id: "39",
    name: "BANANA PRATA KG",
    price: 6.99,
    originalPrice: 6.49,
    // Foto do produto: Banana prata por kg
    image: "https://exemplo.com/imagens/banana-prata-kg.jpg", // Troque para o link da foto real do produto
    category: "Frutas e Verduras",
    description: "Banana prata por kg",
    stock: 8,
    rating: 4.7,
    reviews: 45,
    brand: "Frutas Frescas",
    unit: "kg",
    tags: ["banana", "prata", "fruta"],
  },
  {
    id: "40",
    name: "MAÇÃ FUJI KG",
    price: 9.99,
    originalPrice: 9.49,
    // Foto do produto: Maçã fuji por kg
    image: "https://exemplo.com/imagens/maçã-fuji-kg.jpg", // Troque para o link da foto real do produto
    category: "Frutas e Verduras",
    description: "Maçã fuji por kg",
    stock: 6,
    rating: 4.8,
    reviews: 67,
    brand: "Frutas Frescas",
    unit: "kg",
    tags: ["maçã", "fuji", "fruta"],
  },
  {
    id: "41",
    name: "FRANGO INTEIRO KG",
    price: 12.99,
    originalPrice: 12.49,
    // Foto do produto: Frango inteiro por kg
    image: "https://exemplo.com/imagens/frango-inteiro-kg.jpg", // Troque para o link da foto real do produto
    category: "Carnes e Aves",
    description: "Frango inteiro por kg",
    stock: 10,
    rating: 4.6,
    reviews: 123,
    brand: "Frigorífico",
    unit: "kg",
    tags: ["frango", "inteiro", "carne"],
  },
  {
    id: "42",
    name: "CARNE MOÍDA KG",
    price: 24.99,
    originalPrice: 24.49,
    // Foto do produto: Carne moída por kg
    image: "https://exemplo.com/imagens/carne-moída-kg.jpg", // Troque para o link da foto real do produto
    category: "Carnes e Aves",
    description: "Carne moída por kg",
    stock: 8,
    rating: 4.7,
    reviews: 89,
    brand: "Frigorífico",
    unit: "kg",
    tags: ["carne", "moída", "bovina"],
  },
  {
    id: "43",
    name: "DETERGENTE LÍQUIDO YPE 500ML",
    price: 4.99,
    originalPrice: 4.79,
    // Foto do produto: Detergente líquido Ypê 500ml
    image: "https://exemplo.com/imagens/detergente-líquido-ype-500ml.jpg", // Troque para o link da foto real do produto
    category: "Limpeza",
    description: "Detergente líquido 500ml",
    stock: 25,
    rating: 4.5,
    reviews: 234,
    brand: "Ypê",
    unit: "500ml",
    tags: ["detergente", "líquido", "limpeza"],
  },
  {
    id: "44",
    name: "SABÃO EM PÓ OMO 1KG",
    price: 12.99,
    originalPrice: 12.49,
    // Foto do produto: Sabão em pó Omo 1kg
    image: "https://exemplo.com/imagens/sabão-em-pó-omo-1kg.jpg", // Troque para o link da foto real do produto
    category: "Limpeza",
    description: "Sabão em pó 1kg",
    stock: 15,
    rating: 4.6,
    reviews: 167,
    brand: "Omo",
    unit: "1kg",
    tags: ["sabão", "pó", "limpeza"],
  },
  {
    id: "45",
    name: "SHAMPOO HEAD & SHOULDERS 400ML",
    price: 18.99,
    originalPrice: 18.49,
    // Foto do produto: Shampoo anticaspa Head & Shoulders 400ml
    image: "https://exemplo.com/imagens/shampoo-anticaspa-head-shoulders-400ml.jpg", // Troque para o link da foto real do produto
    category: "Higiene e Beleza",
    description: "Shampoo anticaspa 400ml",
    stock: 12,
    rating: 4.7,
    reviews: 89,
    brand: "Head & Shoulders",
    unit: "400ml",
    tags: ["shampoo", "anticaspa", "cabelo"],
  },
  {
    id: "46",
    name: "PASTA DE DENTE COLGATE 90G",
    price: 3.99,
    originalPrice: 3.79,
    // Foto do produto: Pasta de dente Colgate 90g
    image: "https://exemplo.com/imagens/pasta-de-dente-colgate-90g.jpg", // Troque para o link da foto real do produto
    category: "Higiene e Beleza",
    description: "Pasta de dente 90g",
    stock: 30,
    rating: 4.5,
    reviews: 345,
    brand: "Colgate",
    unit: "90g",
    tags: ["pasta", "dente", "higiene"],
  },
  {
    id: "47",
    name: "PAPEL HIGIÊNICO FOLHA DUPLA NEVE 30M",
    price: 6.99,
    originalPrice: 6.49,
    // Foto do produto: Papel higiênico folha dupla Neve 30m
    image: "https://exemplo.com/imagens/papel-higiênico-folha-dupla-neve-30m.jpg", // Troque para o link da foto real do produto
    category: "Higiene e Beleza",
    description: "Papel higiênico folha dupla 30m",
    stock: 20,
    rating: 4.4,
    reviews: 123,
    brand: "Neve",
    unit: "30m",
    tags: ["papel", "higiene", "folha dupla"],
  },
  {
    id: "48",
    name: "CAFÉ EM PÓ MELITTA 500G",
    price: 15.99,
    originalPrice: 15.49,
    // Foto do produto: Café em pó Melitta 500g
    image: "https://exemplo.com/imagens/café-em-pó-melitta-500g.jpg", // Troque para o link da foto real do produto
    category: "Bebidas",
    description: "Café em pó tradicional 500g",
    stock: 18,
    rating: 4.8,
    reviews: 234,
    brand: "Melitta",
    unit: "500g",
    tags: ["café", "pó", "tradicional"],
  },
  {
    id: "49",
    name: "SUCO DE LARANJA INTEGRAL DEL VALLE 1L",
    price: 8.99,
    originalPrice: 8.49,
    // Foto do produto: Suco de laranja integral Del Valle 1L
    image: "https://exemplo.com/imagens/suco-de-laranja-integral-del-valle-1l.jpg", // Troque para o link da foto real do produto
    category: "Bebidas",
    description: "Suco de laranja integral 1 litro",
    stock: 15,
    rating: 4.6,
    reviews: 89,
    brand: "Del Valle",
    unit: "1L",
    tags: ["suco", "laranja", "integral"],
  },
  {
    id: "50",
    name: "REFRIGERANTE COCA-COLA 2L",
    price: 7.99,
    originalPrice: 7.49,
    // Foto do produto: Refrigerante Coca-Cola 2L
    image: "https://exemplo.com/imagens/refrigerante-coca-cola-2l.jpg", // Troque para o link da foto real do produto
    category: "Bebidas",
    description: "Refrigerante Coca-Cola 2 litros",
    stock: 25,
    rating: 4.7,
    reviews: 456,
    brand: "Coca-Cola",
    unit: "2L",
    tags: ["refrigerante", "cola", "bebida"],
  },
  
  
]

export const categories = [
  "Todos",
  "Grãos",
  "Óleos",
  "Açúcar e Adoçantes",
  "Bebidas",
  "Laticínios",
  "Padaria",
  "Massas",
  "Frutas e Verduras",
  "Carnes e Aves",
  "Limpeza",
  "Higiene e Beleza",
  "Snacks",
  "Chocolates",
  "Hortifruti",
  "Frutas",
  "Carnes",
]

export const promotions: Promotion[] = [
  {
    id: "1",
    title: "Super Oferta de Grãos",
    description: "Até 30% OFF em arroz, feijão e cereais",
    discount: 30,
    validUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    image: "/placeholder.svg?height=200&width=400",
    isActive: true,
  },
  {
    id: "2",
    title: "Combo Café da Manhã",
    description: "Pão + Leite + Café com desconto especial",
    discount: 25,
    validUntil: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    image: "/placeholder.svg?height=200&width=400",
    isActive: true,
  },
  {
    id: "3",
    title: "Limpeza Total",
    description: "Produtos de limpeza com até 40% OFF",
    discount: 40,
    validUntil: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    image: "/placeholder.svg?height=200&width=400",
    isActive: true,
  },
]

export const productPromotions: ProductPromotion[] = [
  {
    id: "1",
    productId: "1",
    productName: "ÁGUA MINERAL NATURAGUA 1,5L",
    originalPrice: 2.30,
    newPrice: 1.99,
    discount: 13,
    image: "https://i.ibb.co/N65dsgfh/aguanaturagua1-5l.jpg",
    isActive: true,
    createdAt: new Date(),
    validUntil: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: "2",
    productId: "4",
    productName: "AMENDOIM EM BANDA CASTRO 1KG",
    originalPrice: 13.49,
    newPrice: 11.99,
    discount: 11,
    image: "https://i.ibb.co/PZ9HLZrg/amendoimembanda.jpg",
    isActive: true,
    createdAt: new Date(),
    validUntil: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
  },
]
